### ISSUE TITLE
multicursors.nvim/lua/multicursors/layers.lua:41: attempt to index field 'opts' (a nil value)

### ISSUE THREAD

**Issue by ttbug** [smoka7/multicursors.nvim#11]
./site/lazy/multicursors.nvim/lua/multicursors/layers.lua:41: attempt to index field 'opts' (a nil value)
stacktrace:
- /multicursors.nvim/lua/multicursors/layers.lua:41 in generate_heads
- /multicursors.nvim/lua/multicursors/layers.lua:129 in generate_normal_heads
- /multicursors.nvim/lua/multicursors/layers.lua:195 in create_normal_hydra
- /multicursors.nvim/lua/multicursors/init.lua:90 in setup

**Comment by smoka7** [comment]
fixed in [6eea6d7](https://github.com/smoka7/multicursors.nvim/commit/6eea6d7e3be52b41b4f63d33d9a877010c436199).
probably you need to update your config.
