### ISSUE TITLE
[Question] Is there any way to select with a speical character?

### ISSUE THREAD

**Issue by tan-wei** [smoka7/multicursors.nvim#33]
Firstly, thanks for this great project.

In other editors, it's very common to do increase selection and then with multi-cursors, we can do insertion、deletion or modification.
For example, in the code below:
```rust
let grid =  [
   ["#","#","#","#","#","#"],
   ["#","T","#","#","#","#"],
   ["#",".",".","B",".","#"],
   ["#",".","#","#",".","#"],
   ["#",".",".",".","S","#"],
   ["#","#","#","#","#","#"]];
```
I will use `[` to select all `[`, then insert it with `vec!`, it will becomes:
```rust
let grid = vec![
    vec!['#', '#', '#', '#', '#', '#'],
    vec!['#', 'T', '#', '#', '#', '#'],
    vec!['#', '.', '.', 'B', '.', '#'],
    vec!['#', '.', '#', '#', '.', '#'],
    vec!['#', '.', '.', '.', 'S', '#'],
    vec!['#', '#', '#', '#', '#', '#']];
```

For `multicursors.nvim`, I try to use `MCunderCursor` and `MCstart`, they do not work as I expect. `MCstart` will work with a whole word (which does not contain any special characters), but does not work with `[`.

So, is there any way to do this? `MCpattern` would do part of this, but it will select ALL instead of part of the matched ones.

Thanks!

**Comment by tan-wei** [comment]
<html><body>


n | [count] Finds the next match after the main selection
-- | --



</body>
</html>

Use n does not occur anything.

**Comment by smoka7** [comment]
You could select `[` in visual mode and  use `MCstart` in your use case.
Running `MCstart` from normal mode wraps the selected pattern in `\<word\>` but not it visual mode.

**Comment by smoka7** [comment]
> 



> n 	[count] Finds the next match after the main selection
> 
> Use n does not occur anything.

It works fine on my side. pressing `4n` finds next 4 selections.

**Comment by tan-wei** [comment]
OK. Got it. [ is a special char in regex, when in normal mode which wraps with '/' will fail to match anything.
Visual mode should be used in this case. So I think some notes should be add into the  document to make it clear for others like me.

Many thanks.




---- Replied Message ----
| From | ***@***.***> |
| Date | 08/11/2023 16:51 |
| To | ***@***.***> |
| Cc | Wei ***@***.***>***@***.***> |
| Subject | Re: [smoka7/multicursors.nvim] [Question] Is there any way to select with a speical character? (Issue #33) |

You could select [ in visual mode and use MCstart in your use case.
Running MCstart from normal mode wraps the selected pattern in \<word\> but not it visual mode.
