### ISSUE TITLE
FR: Switch direction

### ISSUE THREAD

**Issue by chrisgrieser** [smoka7/multicursors.nvim#34]
In visual mode (and in vim-visual-multi), it is possible to switch the direction of the selection by moving back.

This behavior is not possible, with multicursor.nvim I am "blocked" from going any further until I switch anchors with `o`.

https://github.com/smoka7/multicursors.nvim/assets/73286100/0262c4a1-ad7a-4ec4-b36c-16b019f459fb

**Comment by smoka7** [comment]
At first I want it to implement it like this, but i couldn't replicate the behavior nicely.
I accept a PR for this, and help in the process when needed.
