### ISSUE TITLE
Adding multiple cursors to the start of lines and making changes in insert mode causes strange text placement

### ISSUE THREAD

**Issue by joshstobbs** [smoka7/multicursors.nvim#42]
Hey there!

First things first, thank you very much for the plugin it has so far been an incredible implementation of multi-cursor editing!  Second, I have checked the README and read other issues and cannot find reference to something like this.

On to the bug itself, I've found that when I start a multi-cursor sequence at the start of a given line making changes in insert mode puts the added text all out of order.  As this is hard to describe I've attached a video, in that video I'm using a minimal setup, essentially just this plugin and it's dependencies loaded through Lazy.  No keybindings have been added outside of what is created by the plugin.  Of note this is reproduced in my more complex actual editing setup as well.

If you're looking to reproduce it, setup a sequence similar to something like:

```javascript
let foo = "bar"
let bar = "baz"
let baz = "bux"
```

and start the multi-cursor on the first `let`, add successive cursors to the next `let`s and push `c` to change the text, enter any text and it all should go a bit haywire at that point.

**Expected behavior**
Creating multiple cursors on the first word of each line and making insert mode changes should add text in the place where the cursors were created.

**Nvim version:**
Nightly/ NVIM v0.10.0-dev

**Multicursor version:**
v.0.7.4 (latest)

**Screenshots**

https://github.com/smoka7/multicursors.nvim/assets/57326077/83ab0cb0-e96a-4aca-a015-908d3eb2c2c1

**Comment by smoka7** [comment]
Thanks for the through report :+1:. 
There is also a similar issue when inserting at the end of line. I'll merge this fix when i have a solution for that too.

**Comment by joshstobbs** [comment]
Incredible!  Thanks for the update, I'll watch out for the merge.
