### ISSUE TITLE
How to rebind extend mapping?

### ISSUE THREAD

**Issue by bndlfm** [smoka7/multicursors.nvim#45]
This seems to be a simple question but I can't seem to find it. I use Colemak and would like to use e for create_up but I've been unable to find the method used for switching to extend_mode to rebind it. Both disabling and/or rebinding 'e' in normal_keys and/or extend_keys but this doesn't seem to work.

Is this possible?

I've probably missed something silly but I've been troubleshooting this for an embarrassing amount of time.

**Comment by smoka7** [comment]
Nah, unfortunately the `i,a,c,e` keys are hard coded right now.
But I'll fix it soon, sorry for creating a confusion.

**Comment by bndlfm** [comment]
Thank you so much for the quick response. I haven't had the time to finish messing with my config but the branch you pushed seems to work great with the little testing I've done before bed.
