### ISSUE TITLE
show hints in vertical

### ISSUE THREAD

**Issue by bassamsdata** [smoka7/multicursors.nvim#48]
Thank you for this amazing plugin and this work and I'm trying to learn it so I have this question.
- [ x] Did you check Readme and existing issues?
    Yes
**Describe the bug**
It's a question as the title suggests. in horizntal mode the hints are going off the screen sometimes and hard to distiguish between them. as below screenshot:
<img width="1666" alt="Screen Shot 2023-10-09 at 9 27 04 PM" src="https://github.com/smoka7/multicursors.nvim/assets/105807570/643c6c79-9159-42e4-a760-d332d0b77c92">

I never used hydra. I used to use `whichkey` then I'm using now [mini.clue](https://github.com/echasnovski/mini.clue) and it's perfect because it's in vertical mode.
In [hydra readme](https://github.com/anuvyklack/hydra.nvim#hint-1), it's written that we can use it in vertical mode, but I'm not sure why I can't use it with multicursor.nvim. like below screenshot from the readme:
<img width="415" alt="Screen Shot 2023-10-09 at 9 25 56 PM" src="https://github.com/smoka7/multicursors.nvim/assets/105807570/1a220441-cb91-46a2-92da-3c5187bda7dd">

**Expected behavior**
to use the hint in vertical clear way.

**Screenshots**
If it can be vertical hints like mini.clue in
<img width="1665" alt="Screen Shot 2023-10-09 at 9 34 15 PM" src="https://github.com/smoka7/multicursors.nvim/assets/105807570/57b5ff6d-1240-40f1-b669-423f5cd22023">

**Nvim version:**
NVIM v0.9.2
**Multicursor version:**
0.8.1
**Additional context**
MacOS 12.6
hydra commit: ceb1fb7
```lua
    "smoka7/multicursors.nvim",
    dependencies = {
      "smoka7/hydra.nvim",
    },
    opts = {
      hint_config = {
        border = "rounded",
        position = "bottom-left",
      },
    },
```

**Comment by smoka7** [comment]
Hydra creates the window in the right direction but also adjust the window size to the line length.
It's an very easy fix, If you want to create a pr for it, I'll guide you to the right direction.

**Comment by bassamsdata** [comment]
Yea sure, I'll try to do it if you guide me where to do that. thanks

**Comment by smoka7** [comment]
If we can have a `config` for this variable https://github.com/smoka7/multicursors.nvim/blob/c75d0f2594f8faa766682afecd4a6d6fa26b3974/lua/multicursors/layers.lua#L109
users can have a vertical hint like this
```lua
    "smoka7/multicursors.nvim",
    dependencies = {
      "smoka7/hydra.nvim",
    },
    opts = {
      hint_config = {
        border = "rounded",
        position = "bottom-left",
      },
    },            
      generate_hints = {
                normal = true,
                insert = true,
                extend = true,
                column_count = 1,
      },

```
