### ISSUE TITLE
Autocompletion in multicursor insert mode is broken

### ISSUE THREAD

**Issue by Andrew15-5** [smoka7/multicursors.nvim#55]
- [x] Did you check Readme and existing issues?
    
**Describe the bug**
The way this plugin works in multicursor insert mode allows the user to use autocompletion (from LSP server or whatever). But when I actually use this, the plugin inserts autocompleted/suggested (selected) item in addition to already inserted characters. The only correct selection is the primary one (where autocompletion client substitutes what user already have written with the selected item).

**To Reproduce**
![image](https://github.com/smoka7/multicursors.nvim/assets/37143421/998a3eef-a52d-4d6e-87b8-0437611e6c79) ![image](https://github.com/smoka7/multicursors.nvim/assets/37143421/f71d3ac9-f3da-4483-a516-b837519b96ec) ![image](https://github.com/smoka7/multicursors.nvim/assets/37143421/13f0032c-4164-4268-be95-99885c730002) ![image](https://github.com/smoka7/multicursors.nvim/assets/37143421/415359ad-dec9-44a8-bb2f-83f867dc994a)

**Expected behavior**
The inserted text should be replaced by the selected suggested item in all selection, not only in the primary one.

**Nvim version:**
0.9.4

**Multicursor version:**
https://github.com/smoka7/multicursors.nvim/commit/c75d0f2594f8faa766682afecd4a6d6fa26b3974

**Comment by smoka7** [comment]
duplicate #26

**Comment by xzbdmw** [comment]
This seems impossible to address by cmp's side
