### ISSUE TITLE
Multicursor is broken in insert mode in Neovim v0.10.0-dev

### ISSUE THREAD

**Issue by Andrew15-5** [smoka7/multicursors.nvim#67]
- [x] Did you check Readme and existing issues?
    
**Describe the bug**
I needed to switch to latest Neovim version and now suddenly this plugin only inserts at 1 location instead of all locations. I thought that I broke something, or there is a bug in recent update, or I need to update NvChad or I need to remove some other plugins. After 2 minutes, I finally realized that it has to do with a new dev version of Neovim. I have no idea what causes this bug, but if the non-dev version will still behave the same way, then this plugin won't be compatible with Neovim v0.10.0. You probably should look into this.

**To Reproduce**

Download Neovim pre-release version 0.10.0 from GitHub Release page and add basic setup:

```lua 
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'

if not vim.uv.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--depth',
        '1',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    }
end

vim.opt.runtimepath:prepend(lazypath)
require('lazy').setup({
    "smoka7/multicursors.nvim",
    event = "VeryLazy",
    dependencies = {
        'nvim-treesitter/nvim-treesitter',
        'smoka7/hydra.nvim',
    },
    opts = {},
    cmd = { 'MCstart', 'MCvisual', 'MCclear', 'MCpattern', 'MCvisualPattern', 'MCunderCursor' },
}, opts)
```

**Expected behavior**
New characters should appear in all selected location instead of just one.

**Screenshots**
_unnecessary_

**Nvim version:** 0.10.0-dev-9af03bc

**Multicursor version:** 0.10.1

**Additional context**
This bug also causes an auto-save plugin to stop auto saving. Only nvim re-open will fix this.

**Comment by smoka7** [comment]
I can't reproduce this in latest nvim nightly release.

**Comment by Andrew15-5** [comment]
@smoka7, try following an updated reproduction instruction.

**Comment by smoka7** [comment]
Our test are passing in the nvim nightly and stable https://github.com/smoka7/multicursors.nvim/actions/runs/6957221416 .

**Comment by Andrew15-5** [comment]
You know that test don't always represent reality. Try my steps and tell why manual/realistic test fail, but automatic/headless test succeed.

<details><summary>tests/custom.lua</summary>

```lua
local utils = require 'multicursors.utils'
local search = require 'multicursors.search'
local insert_mode = require 'multicursors.insert_mode'
local config = require 'multicursors.config'
local api = vim.api
local assert = require 'luassert'

local paragraph = {
    'word',
    'word',
    'word',
    'word',
}

describe('inserts mode', function()
    before_each(function()
        vim.cmd [[enew]]
        api.nvim_buf_set_lines(0, 0, -1, false, paragraph)
        local buffer = api.nvim_buf_get_lines(0, 0, -1, false)
        search.find_all_matches(buffer, 'word', 0, 0)
        vim.cmd [[w! before]]
    end)

    after_each(function()
        vim.cmd [[w! after]]
        vim.cmd.bdelete { bang = true }
    end)

    it('inserts text', function()
        local selections = utils.get_all_selections()
        assert.equal(#selections, 3)

        insert_mode.insert(config)
        vim.cmd 'normal! ia '
        insert_mode.exit()

        local buffer = api.nvim_buf_get_lines(0, 0, -1, false)
        utils.clear_selections()
        search.find_all_matches(buffer, 'a word', 0, 0)
        selections = utils.get_all_selections()
        assert.equal(#selections, 3)
    end)
end)
``` 
</details> 

```sh
# Doesn't fail
nvim --headless --noplugin -u tests/minimal_init.lua -c "PlenaryBustedFile tests/custom.lua"
```

In `Dockerfile` I added `version` argument:

```Dockerfile
ARG version=nightly # nightly|stable
RUN wget https://github.com/neovim/neovim/releases/download/$version/nvim.appimage \
```

If I use `nightly` (v0.10.0) then the test fails, if I use `stable` (v0.9.4) then the test succeeds. I literally only change the version of Neovim and result changes, therefore your test doesn't represent real UX (even though I like how automatic tests are run/executed).

**Comment by smoka7** [comment]
Your test passes on my machine and  even on the ci https://github.com/smoka7/multicursors.nvim/pull/71.

**Comment by Andrew15-5** [comment]
> Your test passes on my machine and even on the ci #71.

Of course it passes, I said so myself:

> ```shell
> # Doesn't fail
> nvim --headless --noplugin -u tests/minimal_init.lua -c 'PlenaryBustedFile tests/custom.lua'
> ```

This is an automatic test that works on both versions. The only test that doesn't pass is the manual one, source for which is in the [multicursors.zip](https://github.com/smoka7/multicursors.nvim/files/13440231/multicursors.zip) (included in the OP).

**Comment by smoka7** [comment]
I meant both tests also. Nothing I can do about this.

**Comment by Andrew15-5** [comment]
> I meant both tests also

So you are saying that you (just to be 100% clear):
1. downloaded the zip;
2. run the shell oneliner that builds Docker image and runs/creates the container;
3. inside the container and inside the automatically opened Neovim with the simple test case pressed `ia `;
4. and in the end all 4 lines were modified (not just one)?

This sounds impossible, since the whole point of creating the Docker image + container is to eliminate all variables. So we both have to have the same experience inside the container. I specifically re-build the image with `--no-cache` just now, and the issue still persists with `version=nightly`.

**Comment by Andrew15-5** [comment]
I updated the zip archive. Now you can either write `just` or `just nightly` (or `just n`) to open the `file` in Neovim nightly version. Or you can write `just stable` (or `just s`) to open the `file` in Neovim stable version. With `just` the plugin **does not work** as expected. With `just stable` the plugin **does work** as expected.

Here is a screen record:

https://github.com/smoka7/multicursors.nvim/assets/37143421/4ec25583-567e-4b17-95f8-e0ec6678b39d

**Comment by doongjohn** [comment]
I'm having the same issue with the nightly version

**Comment by smoka7** [comment]
I reproduced this today, for a fix update hydra to latest commit https://github.com/smoka7/hydra.nvim  or disable hints.
