### ISSUE TITLE
Documentation suggests normal multicursor mode "u" is bound to both "lowercase" and "undo"

### ISSUE THREAD

**Issue by doulighan** [smoka7/multicursors.nvim#85]
The Normal mode keymaps dropdown says "u" is bound to both, however in config.lua it appears there is no "undo" function outside of Extend mode. 

Pretty new to neovim, so maybe I'm missing something! But I can't find a way to undo insert mode changes, outside of exiting multicursor completely and sending a bunch of undo events.

![multi](https://github.com/smoka7/multicursors.nvim/assets/16358780/32875272-3671-4040-998a-b300c7c4915c)

**Comment by smoka7** [comment]
You're right, I'll push a fix.
